version: "3"

tasks:
  up:
    desc: "Запустить все сервисы"
    cmds:
      - docker compose -f deploy/order/docker-compose.yml up -d
      - docker compose -f deploy/inventory/docker-compose.yml up -d
      - docker compose -f deploy/core/docker-compose.yml up -d

  down:
    desc: "Остановить все сервисы"
    cmds:
      - docker compose -f deploy/order/docker-compose.yml down
      - docker compose -f  deploy/inventory/docker-compose.yml down
      - docker compose -f deploy/core/docker-compose.yml down

  logs:
    desc: "Показать логи всех сервисов"
    cmds:
      - docker compose -f order-service/docker-compose.yml logs -f &
      - docker compose -f inventory-service/docker-compose.yml logs -f &
      - docker compose -f payment-service/docker-compose.yml logs -f

  restart:
    desc: "Перезапустить все сервисы"
    cmds:
      - task: down
      - task: up
