// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order-service/internal/repository/model"

	mock "github.com/stretchr/testify/mock"
)

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

// ListParts provides a mock function with given fields: ctx, partIDs
func (_m *InventoryService) ListParts(ctx context.Context, partIDs []string) ([]*model.Part, error) {
	ret := _m.Called(ctx, partIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Part, error)); ok {
		return rf(ctx, partIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Part); ok {
		r0 = rf(ctx, partIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, partIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
