// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order-service/internal/repository/model"

	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

// MakePayment provides a mock function with given fields: ctx, orderID, userID, pm
func (_m *PaymentService) MakePayment(ctx context.Context, orderID string, userID string, pm *model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, orderID, userID, pm)

	if len(ret) == 0 {
		panic("no return value specified for MakePayment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.PaymentMethod) (string, error)); ok {
		return rf(ctx, orderID, userID, pm)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.PaymentMethod) string); ok {
		r0 = rf(ctx, orderID, userID, pm)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderID, userID, pm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
