// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	inventorypb "inventory-service/grpc/inventorypb"

	mock "github.com/stretchr/testify/mock"
)

// PartRepo is an autogenerated mock type for the PartRepo type
type PartRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *PartRepo) Get(ctx context.Context, uuid string) (*inventorypb.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *inventorypb.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*inventorypb.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *inventorypb.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventorypb.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *PartRepo) List(ctx context.Context, filter *inventorypb.PartsFilter) ([]*inventorypb.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*inventorypb.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventorypb.PartsFilter) ([]*inventorypb.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventorypb.PartsFilter) []*inventorypb.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*inventorypb.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventorypb.PartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPartRepo creates a new instance of PartRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepo {
	mock := &PartRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
